title: <p align="center"> Luthfi Raditya </p>

logo: "/images/ProfilePicture.png?raw=true"

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1gkyx6fNLXsmGM3ZnaT7dXRQKen04P6t8EmyYiVxsNp0/edit?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/luthfiraditya/">LinkedIn</a> |
  <a href="https://github.com/luthfiraditya">GitHub</a>
  </p>
  
  <p align="justify">
  I am an aspiring Data Scientist with a passion for using business, data, and technology to create something that positively impacts society. I have a deep specialization in constructing machine learning models, which makes me a T-shaped individual.

  <br><br>
  I blog about AI/ML/Data Science and my personal experience. Outside of work, I enjoy sports, reading non-fiction, and binge-watching!
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
