title: <p align="center"> Luthfi Raditya </p>

logo: "/images/247372.jpg?raw=true"

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1tLnYIh6dF0sAzoN-vq_T8l34EdpQQKwDca7sMG27PxA/edit?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/luthfiraditya/">LinkedIn</a> |
  <a href="https://github.com/luthfiraditya">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing Bachelor degree in Information System at Airlangga University.
  <br><br>
  I am an aspiring Data Scientist with a passion for using business, data, and technology to create something that positively impacts society
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
