title: <p align="center"> Luthfi Raditya </p>

logo: "/images/ProfilePicture.png?raw=true"

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1ngbYHxtf9XfROKlS22Tb3WLjl8ZYc_IK/view?usp=sharing" target="_blank">Resume</a> |
  <a href="https://www.linkedin.com/in/luthfiraditya/" target="_blank">LinkedIn</a> |
  <a href="https://github.com/luthfiraditya" target="_blank">GitHub</a> |
  <a href="https://medium.com/@luthfirdty" target="_blank">Medium</a>
  
  </p>
  
  <p align="justify">
  I am an aspiring Data Scientist with a passion for using business, data, and technology to create something that positively impacts society. I have a deep specialization in constructing machine learning models, which makes me a  T-shaped individual.

  <br><br>
  I blog about AI/ML/Data Science and my personal experience. Outside of work, I enjoy sports, reading non-fiction, and binge-watching!
  <br><br>
  </p>

  
theme: jekyll-theme-minimal
